apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer-bacheca-com
spec:
  replicas: 1
  selector:
    matchLabels:
      name: orderer-bacheca-com
  template:
    metadata:
      labels:
        name: orderer-bacheca-com
    spec:
      volumes:
      - name: fabricfiles
        persistentVolumeClaim:
          claimName: fabric-pvc-or

      containers:
      - name: orderer-bacheca-com
        image: "hyperledger/fabric-orderer:2.0.0"
        command: ["sh", "-c", "orderer"]
        env:
        - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
          value: /fabric/organizations/ordererOrganizations/bacheca.com/orderers/orderer-bacheca-com/tls/server.crt
        - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
          value: /fabric/organizations/ordererOrganizations/bacheca.com/orderers/orderer-bacheca-com/tls/server.key
        - name: ORDERER_GENERAL_CLUSTER_ROOTCAS
          value: "[/fabric/organizations/ordererOrganizations/bacheca.com/orderers/orderer-bacheca-com/tls/ca.crt]"
        - name: ORDERER_GENERAL_GENESISFILE
          value: /fabric/system-genesis-block/genesis.block
        - name: ORDERER_GENERAL_BOOTSTRAPMETHOD
          value: file
        - name: ORDERER_GENERAL_BOOTSTRAPFILE
          value: /fabric/system-genesis-block/genesis.block
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_LISTENPORT
          value: "7050"
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /fabric/organizations/ordererOrganizations/bacheca.com/orderers/orderer-bacheca-com/msp
        - name: ORDERER_GENERAL_LOCALMSPID
          value: OrdererMSP
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: /fabric/organizations/ordererOrganizations/bacheca.com/orderers/orderer-bacheca-com/tls/server.crt
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "true"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: /fabric/organizations/ordererOrganizations/bacheca.com/orderers/orderer-bacheca-com/tls/server.key
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: "[/fabric/organizations/ordererOrganizations/bacheca.com/orderers/orderer-bacheca-com/tls/ca.crt]"
        - name: ORDERER_CFG_PATH
          value: /fabric/
        - name: ORDERER_GENERAL_LEDGERTYPE
          value: file
        - name: ORDERER_FILELEDGER_LOCATION
          value: /fabric/ledger/orderer
        - name: ORDERER_GENERAL_BATCHTIMEOUT
          value: 1s
        - name: ORDERER_GENERAL_BATCHSIZE_MAXMESSAGECOUNT
          value: "10"
        - name: ORDERER_GENERAL_MAXWINDOWSIZE
          value: "1000"
        - name: CONFIGTX_GENERAL_ORDERERTYPE
          value: etcdraft
        volumeMounts:
        - mountPath: /fabric
          name: fabricfiles
        ports:
        - containerPort: 7050


---
apiVersion: v1
kind: Service
metadata:
  name: orderer-bacheca-com
  labels:
    run: orderer-bacheca-com
spec:
  type: ClusterIP
  selector:
    name: orderer-bacheca-com
  ports:
  - name: grpc
    port: 7050
    protocol: TCP
  - name: endor
    port: 7051
    protocol: TCP
