kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fabric-pvc-tf1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: general