kind: PersistentVolume
apiVersion: v1
metadata:
  name: fabric-pv
  labels:
    name: fabricfiles
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/fabric
    server: storage.bacheca.com
    readOnly: false