apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: bigmarket-richiedente-bacheca-com
  name: bigmarket-richiedente-bacheca-com
spec:
  ports:
  - name: "7051"
    port: 7051
    targetPort: 7051
  selector:
    io.kompose.service: bigmarket-richiedente-bacheca-com
status:
  loadBalancer: {}
