apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: bigmarket-richiedente-bacheca-com-claim5
  name: bigmarket-richiedente-bacheca-com-claim5
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
