apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: garden-forn1-bacheca-com
  name: garden-forn1-bacheca-com
spec:
  ports:
  - name: "9051"
    port: 9051
    targetPort: 9051
  selector:
    io.kompose.service: garden-forn1-bacheca-com
status:
  loadBalancer: {}
