apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: tech-forn2-bacheca-com
  name: tech-forn2-bacheca-com
spec:
  ports:
  - name: "10051"
    port: 10051
    targetPort: 10051
  selector:
    io.kompose.service: tech-forn2-bacheca-com
status:
  loadBalancer: {}
