apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: tech-forn1-bacheca-com
  name: tech-forn1-bacheca-com
spec:
  ports:
  - name: "8051"
    port: 8051
    targetPort: 8051
  selector:
    io.kompose.service: tech-forn1-bacheca-com
status:
  loadBalancer: {}
